### ISSUE TITLE
[bug]: Mastodon repeatedly crashes on startup after migration from 02x

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/mastodon-wrapper#11]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

![Screen Shot 2022-01-14 at 6 30 48 PM](https://user-images.githubusercontent.com/45926711/149605928-f9bdce2f-94fc-427a-ac50-415ac4ac96bb.png)
![Screen Shot 2022-01-14 at 6 30 59 PM](https://user-images.githubusercontent.com/45926711/149605935-658e31fe-1b9a-4516-9ffc-873a3e8ae3af.png)
![Screen Shot 2022-01-14 at 6 31 08 PM](https://user-images.githubusercontent.com/45926711/149605941-0ccb95fc-26ae-43b0-9db5-a68b1848ae89.png)
![Screen Shot 2022-01-14 at 6 31 16 PM](https://user-images.githubusercontent.com/45926711/149605945-f5033482-2c0f-4aa6-9552-92f4a6ad2cd6.png)

From the logs:

2022-01-15T02:43:10.145215Z 2022-01-15 02:43:10.144 UTC [41] FATAL:  data directory "/root/persistence/pgdata" has invalid permissions
2022-01-15T02:43:10.145895Z 2022-01-15 02:43:10.144 UTC [41] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).

### Expected Behavior

.

### Steps to Reproduce

Recover Mastodon from 02x and fire it up.

**Comment by chrisguida** [comment]
@BitcoinMechanic please follow these steps to update your prodbox mastodon instance and let me know if this error is still happening:

1. Stop mastodon
2. backup mastodon datadir (`/embassy-data/package-data/volumes/mastodon/data/main/`) to `/embassy-data/package-data` (name the backup directory whatever you want)
3. Install new mastodon from beta (`embassy-cli package install mastodon`)
4. manually invoke migration script (`docker run -it --rm --mount type=bind,src=/embassy-data/package-data/volumes/mastodon/data/main,dst=/root/persistence start9/mastodon/pg-migrate:3.4.1`)
5. Start mastodon once the migration completes

**Comment by BitcoinMechanic** [comment]
This all worked. Had to `chmod 700 pgdata` to get the fourth command there working. This might be unique to my awkward CIFS migration that involved copying my old SSD data (I was running 02x off an SSD) to a linux VM on a mac, then copying over to the mac internal drive then sharing that final directory and migrating using that.

**Comment by chrisguida** [comment]
Tracking @BitcoinMechanic's issues here:

- chmod when coming from CIFS
- sign-in token when you haven't signed in in a long time
- images are not displaying

**Comment by BitcoinMechanic** [comment]
Re: second issue there - it's complaining about a new device, not the time elapsed since last login. Confirmed by not needing token when I went back to my 02x box.

**Comment by dr-bonez** [comment]
>     * chmod when coming from CIFS

It's likely that this happened because it got transferred through a filesystem that didn't support file permissions, likely nothing to do with CIFS.

**Comment by chrisguida** [comment]
> Re: second issue there - it's complaining about a new device, not the time elapsed since last login. Confirmed by not needing token when I went back to my 02x box.

Didn't the message say "it's been a while since you last logged in"?

**Comment by BitcoinMechanic** [comment]
No

![Screen Shot 2022-01-18 at 6 18 50 PM](https://user-images.githubusercontent.com/45926711/150414264-d4eb5746-f62c-4819-aa96-24a07f7263b8.png)
d

**Comment by chrisguida** [comment]
Yeah, "you haven't logged in in a while". That means that if you've recently logged in, this won't happen

**Comment by chrisguida** [comment]
P2ing this until someone else runs into it

**Comment by ProofOfKeags** [comment]
OK so what's going on here?

**Comment by BitcoinMechanic** [comment]
> This all worked. Had to `chmod 700 pgdata` to get the fourth command there working. This might be unique to my awkward CIFS migration that involved copying my old SSD data (I was running 02x off an SSD) to a linux VM on a mac, then copying over to the mac internal drive then sharing that final directory and migrating using that.

Wrong permissions basically. Punt until we start dealing with CIFS migrations from SSD based 0.2x users?

**Comment by ProofOfKeags** [comment]
I meant really about the fact that it was closed and immediately reopened. I should have specified.

**Comment by chrisguida** [comment]
Waiting until there's been a resolution to close.

**Comment by MattDHill** [comment]
I misunderstood something, just a mistake

**Comment by BitcoinMechanic** [comment]
I think we can close this. No one is about to migrate from 0.2.x using CIFS via a mac like I did.
