### ISSUE TITLE
bug: pictures do not load after migration

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/mastodon-wrapper#14]
![Screen Shot 2022-01-20 at 3 07 30 PM](https://user-images.githubusercontent.com/45926711/150436459-5984e737-b21a-4664-a4e1-c61f3184e2f9.png)

**Comment by chrisguida** [comment]
@BitcoinMechanic are there any errors in the logs? What about in the console/network tabs?

**Comment by BitcoinMechanic** [comment]
This was a permissions issue likely related to my non-standard migration. Probably fine to close this.
