### ISSUE TITLE
Firefox beta and mastodon 

### ISSUE THREAD

**Issue by cryptovigilante** [Start9Labs/mastodon-wrapper#16]
When trying to sign on with Firefox beta and tor enabled after logging in I get this screen.
![image1](https://user-images.githubusercontent.com/77592436/150891256-2385ad5b-1392-4f77-9c51-3991ec47c224.png)

Even with enhanced tracking protection off for that page as well as if I turn it off completely.

**Comment by kn0wmad** [comment]
This is reproducible on desktop as well.  Tor Browser works fine - recommend using Tor Browser as a workaround at this time while we discover the source of the issue

**Comment by cryptovigilante** [comment]
Sorry images does not work fine using tor browser either…..

**Comment by kn0wmad** [comment]
> Try switching on allowlist_onions instead of whitelist_onions. This has worked for some people

This should be the fix.  If this works for you @cryptovigilante, we can close this ticket

**Comment by cryptovigilante** [comment]
Yes that worked for me, sorry it took so long to try it and get back to you. Close the ticket.

>>

**Comment by kn0wmad** [comment]
No worries, thank you
