### ISSUE TITLE
mastodon for 0.3.0

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/mastodon-wrapper#4]
update to new package format for 0.3.0

- [x] backup create
- [x] backup restore
- [x] configure
- [x] actions
- [x] health checks
- [x] start
- [x] stop
- [x] install
- [x] uninstall

Edit: TODO: Fix migrations: https://github.com/Start9Labs/mastodon-wrapper/issues/10

**Comment by elvece** [comment]
@chrisguida will you update the tasks with the ones you have completed?

**Comment by chrisguida** [comment]
Everything is done except migrations
