### ISSUE TITLE
Healthcheck complains while Mastodon starts up.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/mastodon-wrapper#7]
![Screen Shot 2021-11-24 at 4 16 26 PM](https://user-images.githubusercontent.com/45926711/143328555-0001d859-c074-45e0-94a5-e60139f4f7ef.png)

**Comment by chrisguida** [comment]
Fixed by eba6a45a58b9f175bcc5d3dbe98e549313e621d4
